rng default; 
addpath ../Replicablility_Majed/Replicable-Difference/
addpath ../SignifFreqExtract_Emily/

alpha=-1; nSamples=1000; nTrials=50; nChannels=10;
cond1=permute(reshape(...
    ColoredNoise(-alpha,nSamples,nTrials*nChannels),...
    [nSamples,nTrials,nChannels]),[2 3 1]); 
cond2=permute(reshape(...
    ColoredNoise(-alpha,nSamples,nTrials*nChannels),...
    [nSamples,nTrials,nChannels]),[2 3 1]); 
params=struct(...
    'divergFunc',@dPrime,...
    'divergTh',.3,...
    'neighborMat',ones(size(cond1,3),size(cond1,3)),...
    'neighborMatTh',.5,...
    'nMinClustLen',0,...
    'nMaxGapUnify',0,...
    'pMax4signif',0.05,...
    'bUnifyPosNeg',false,...
    'nIter',1000);
DiffCondsSignif(cond1,cond2,params);